version: "3.7"

services:

  portal:
    container_name: operational_portal
    build:
      context: ./resources
    ports:
      - 80:80
    volumes:
      - ./portal:/var/www/html/portal/
      - ./resources/portal/TranslationsModel.php:/var/www/html/portal/application/models/TranslationsModel.php
      - ./resources/portal/MY_Controller.php:/var/www/html/portal/application/core/MY_Controller.php
      - ./resources/portal/conf.json:/var/www/html/portal/conf.json
      - ./portal_servicos:/var/www/html/portal_servicos/
      - ./resources/html/index.php:/var/www/html/index.php
    extra_hosts:
      - "host.docker.internal:host-gateway"
